### ISSUE TITLE
Wrong license for Ukrainian dictionary

### ISSUE THREAD

**Issue by FnTm** [wooorm/dictionaries#33]
The Ukrainian dictionary license situation seems to be a bit confusing.
It states that dictionary files themselves are [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://github.com/brown-uk/dict_uk#%D0%BB%D1%96%D1%86%D0%B5%D0%BD%D0%B7%D1%96%D1%8F), and only the scripts building them are GPL3 .

I'll be the first one to say that I'm not an expert in OS licensing, but if I'm right, then a change of license in this project should be in order.

**Comment by wooorm** [comment]
It doesn’t say “dictionary files” and “scripts”, it says “Dictionary data” and “software”.

“Dictionary data” to me reads as lists of words — the input word lists. I’d perhaps put the generated `.dic`, and especially the `.aff` file, in “software”.

Also seems like the hunspell version is MPL instead of GPL: https://github.com/brown-uk/dict_uk/tree/master/distr/hunspell 🤔

**Comment by FnTm** [comment]
Understood. I'll definitely defer to you on this topic, since the whole topic of OS licenses is... complicated, and if you feel that the current license is good - so do I. I just wanted to bring this topic up for additional set of eyes!
