### ISSUE TITLE
using with nspell error

### ISSUE THREAD

**Issue by kyapo33** [wooorm/dictionaries#67]
`import fr from 'dictionary-fr
const dict = nspell(fr);`

when i try to use the dictionnary with nspell i have this type error 

` Argument of type 'Dictionary' is not assignable to parameter of type 'Dictionary | Dictionary[]'.
      Type 'import("/Users/yapokevin/Desktop/next-project/project/node_modules/dictionary-fr/index").Dictionary' is not assignable to type 'Dictionary'.
        Types of property 'aff' are incompatible.
          Type 'Uint8Array' is not assignable to type 'string | Buffer'.
            Type 'Uint8Array' is missing the following properties from type 'Buffer': write, toJSON, equals, compare, and 66 more`
            
            and even if i use `const dict = nspell(fr.aff, fr.dic)`;
 or `const dict = nspell(fr.aff.buffer, fr.dic.buffer);`
 its not working

**Comment by wooorm** [comment]
Update Node and all dependencies. Or share what versions you‘re on. Also: `@ts-expect-error`, it should work.

**Comment by YoannBuzenet** [comment]
It is because index.d.ts in dictionnary-en defines `aff` and `dic` as `Uint8Array` wheras npell wants a string or a buffer.

Here : 

```
export type Dictionary = {
    /**
     *   Data for the affix file (defines the language, keyboard, flags, and more).
     */
    aff: Uint8Array;
    /**
     *   Data for the dictionary file (contains words and flags applying to those words).
     */
    dic: Uint8Array;
};
```

 But, if you log `dic` and `aff`, you get a buffer! So the types declared in this file are not good.

With this, it will correct the bad types : 

`const spell = nspell(en.aff as unknown as Buffer, en.dic as unknown as Buffer);`
